# Generated by Django 5.1.2 on 2024-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.ImageField(default=1, upload_to='pages/banners/'),
            preserve_default=False,
        ),
    ]
